name: lore-cpu
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pytorch=2.1.0  # or 2.0.1 for wider compatibility; 2.7.0 is very recent
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - filelock=3.18.0
  - fsspec=2025.3.2
  - jinja2=3.1.6
  - markupsafe=3.0.2
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy=2.2.5
  - pyparsing=3.2.3
  - rdflib=7.1.4
  - sympy=1.14.0
  - typing_extensions=4.13.2
