name: lore-gpu
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pytorch=2.7.0
  - torchvision
  - torchaudio
  - cudatoolkit=12.1
  - filelock=3.18.0
  - fsspec=2025.3.2
  - jinja2=3.1.6
  - markupsafe=3.0.2
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy=2.2.5
  - pyparsing=3.2.3
  - rdflib=7.1.4
  - sympy=1.14.0
  - typing_extensions=4.13.2
